use [AutoAuctionDB]
CREATE TABLE Users(
ID INT IDENTITY(1,1),
Username VARCHAR(64),
PasswordHash VARCHAR(64) NOT NULL,
UserZipCode VARCHAR(8),
Balance DECIMAL(12,2),
ZipcodeSeller VARCHAR(8)
PRIMARY KEY(Username)
)

CREATE TABLE PrivateUser(
ID INT IDENTITY(1,1),
Username VARCHAR(64) FOREIGN KEY (Username) REFERENCES Users(Username) ON UPDATE CASCADE,
CPRNumber VARCHAR(10) NOT NULL,
PRIMARY KEY(ID))

CREATE TABLE CorporateUser(
ID INT IDENTITY(1,1),
Username VARCHAR(64) FOREIGN KEY REFERENCES Users(Username) ON UPDATE CASCADE,
CVRNumber VARCHAR(12) NOT NULL,
Credit MONEY,
PRIMARY KEY(ID)
)