use [AutoAuctionDB]
CREATE TABLE Users(
ID INT IDENTITY(1,1),
Username VARCHAR(64),
Password VARCHAR(64) NOT NULL,
PRIMARY KEY(Username)
)

CREATE TABLE PrivateUser(
ID INT IDENTITY(1,1),
Username VARCHAR(64) FOREIGN KEY REFERENCES Users(Username),
CPRNumber VARCHAR(10) NOT NULL,
PRIMARY KEY(ID))

CREATE TABLE CorporateUser(
ID INT IDENTITY(1,1),
Username VARCHAR(64) FOREIGN KEY REFERENCES Users(Username),
CVRNumber VARCHAR(12) NOT NULL,
Credit MONEY,
PRIMARY KEY(ID)
)